# Gruvbox Dark Hard Full Theme
[manager]
cwd = { fg = "#8ec07c" } # Aqua

# Hovered
hovered         = { fg = "#1d2021", bg = "#fabd2f" } # Yellow
preview_hovered = { fg = "#1d2021", bg = "#ebdbb2" } # Text

# Find
find_keyword  = { fg = "#fe8019", italic = true } # Orange
find_position = { fg = "#d3869b", bg = "reset", italic = true } # Purple

# Markers
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" } # Green
marker_cut      = { fg = "#fb4934", bg = "#fb4934" } # Red
marker_marked   = { fg = "#83a598", bg = "#83a598" } # Blue
marker_selected = { fg = "#fabd2f", bg = "#fabd2f" } # Yellow

# Tab count
count_copied   = { fg = "#1d2021", bg = "#b8bb26" }
count_cut      = { fg = "#1d2021", bg = "#fb4934" }
count_selected = { fg = "#1d2021", bg = "#fabd2f" }

border_symbol = "│"
border_style  = { fg = "#665c54" } # Gray

[tabs]
active   = { fg = "#1d2021", bg = "#ebdbb2", bold = true }
inactive = { fg = "#ebdbb2", bg = "#3c3836" }

[mode]
normal_main = { fg = "#1d2021", bg = "#fabd2f", bold = true }
normal_alt  = { fg = "#fabd2f", bg = "#282828"}

select_main = { fg = "#1d2021", bg = "#b8bb26", bold = true }
select_alt  = { fg = "#b8bb26", bg = "#282828"}

unset_main  = { fg = "#1d2021", bg = "#fb4934", bold = true }
unset_alt   = { fg = "#fb4934", bg = "#282828"}

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#83a598", bg = "#3c3836" }
progress_error  = { fg = "#fb4934", bg = "#3c3836" }

perm_type  = { fg = "#83a598" }
perm_read  = { fg = "#fabd2f" }
perm_write = { fg = "#fb4934" }
perm_exec  = { fg = "#b8bb26" }
perm_sep   = { fg = "#928374" }

[input]
border   = { fg = "#fabd2f" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#fabd2f" }
active   = { fg = "#d3869b" }
inactive = {}

[confirm]
border     = { fg = "#fabd2f" }
title      = { fg = "#fabd2f" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#fabd2f" }

[tasks]
border  = { fg = "#fabd2f" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#282828" }
cand            = { fg = "#8ec07c" }
rest            = { fg = "#928374" } 
desc            = { fg = "#d3869b" }
separator       = "  "
separator_style = { fg = "#504945" }

[help]
on      = { fg = "#8ec07c" }
run     = { fg = "#d3869b" }
desc    = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer  = { fg = "#ebdbb2", bg = "#3c3836" }

[notify]
title_info  = { fg = "#83a598" }
title_warn  = { fg = "#fabd2f" }
title_error = { fg = "#fb4934" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "#8ec07c" },
	{ mime = "{audio,video}/*", fg = "#fabd2f" },

	# Archives
	{ mime = "application/*zip", fg = "#d3869b" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d3869b" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#83a598" },

	# Fallback
	{ name = "*", fg = "#ebdbb2" },
	{ name = "*/", fg = "#fabd2f" }
]

[spot]
border = { fg = "#fabd2f" }
title  = { fg = "#fabd2f" }
tbl_cell = { fg = "#fabd2f", reversed = true }
tbl_col = { bold = true }
